# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9dcbe1b151d376903879898aec42eeda"
name = "remix-meetup"
handle = "remix-meetup"
application_url = "https://coin-trades-voyeurweb-cast.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "yallaletscode-livestream.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://coin-trades-voyeurweb-cast.trycloudflare.com/auth/callback",
  "https://coin-trades-voyeurweb-cast.trycloudflare.com/auth/shopify/callback",
  "https://coin-trades-voyeurweb-cast.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
